// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjV-PMqdRtMkpklt7oTnm8azvxIudvcZA',
    appId: '1:790545866377:web:c85d6a03c865471cd77058',
    messagingSenderId: '790545866377',
    projectId: 'barberapp-89ce3',
    authDomain: 'barberapp-89ce3.firebaseapp.com',
    storageBucket: 'barberapp-89ce3.appspot.com',
    measurementId: 'G-N8MMNNJ103',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACV-lFcP5vZSnZ-DqYOjVtVc7icmNuhnw',
    appId: '1:790545866377:android:053aacdb62ff912dd77058',
    messagingSenderId: '790545866377',
    projectId: 'barberapp-89ce3',
    storageBucket: 'barberapp-89ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdcKj53TB9EfRCfS5LIWitRF5q621QRow',
    appId: '1:790545866377:ios:cd8972b99fabda15d77058',
    messagingSenderId: '790545866377',
    projectId: 'barberapp-89ce3',
    storageBucket: 'barberapp-89ce3.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdcKj53TB9EfRCfS5LIWitRF5q621QRow',
    appId: '1:790545866377:ios:cd8972b99fabda15d77058',
    messagingSenderId: '790545866377',
    projectId: 'barberapp-89ce3',
    storageBucket: 'barberapp-89ce3.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjV-PMqdRtMkpklt7oTnm8azvxIudvcZA',
    appId: '1:790545866377:web:2410499c7d13dbbfd77058',
    messagingSenderId: '790545866377',
    projectId: 'barberapp-89ce3',
    authDomain: 'barberapp-89ce3.firebaseapp.com',
    storageBucket: 'barberapp-89ce3.appspot.com',
    measurementId: 'G-J9P2L09H21',
  );
}
